version: '3.8'

services:
  app:
    build:
      context: ./app
    container_name: spring-app
    ports:
      - "8010:8010"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/ssl:/etc/ssl/icoinmanage
    depends_on:
      app:
        condition: service_healthy
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
